### PR TITLE
Add ability to provide extra variables through stdin

### PR DESCRIPTION
**Pull request by cellofellow**
I was looking for a way to provide secrets from a pipeline and this looks like it will be just the ticket.

### CODE REVIEW

**Comment by tazjin** [comment]
Hey,

thanks for the contribution. I've just [added a document](https://github.com/tazjin/kontemplate/blob/master/CONTRIBUTING.md) with some notes about contributions to my projects in the repo. This should've been in place some time ago already, sorry about that :)

Please take a look and restructure the commits appropriately.

Other question, is there a reason for adding the documentation file rendered as HTML?

Cheers!

**Comment by cellofellow** [comment]
> Other question, is there a reason for adding the documentation file rendered as HTML?

Oops, didn't notice that had been added.

**Comment by tazjin** [comment]
@cellofellow I would like to do this in a slightly different way. The thing that bothers me about adding features that "take up" resources like `stdin` is always that you implicitly establish an API "contract" for it and say "this is what reading from `stdin` will *always* mean".

An alternative way would be this patch:

```diff
diff --git a/context/context.go b/context/context.go
index 9996f31..fa41f80 100644
--- a/context/context.go
+++ b/context/context.go
@@ -58,7 +58,7 @@ func contextLoadingError(filename string, cause error) error {
 // Attempt to load and deserialise a Context from the specified file.
 func LoadContextFromFile(filename string) (*Context, error) {
 	var c Context
-	err := util.LoadJsonOrYaml(filename, &c)
+	err := util.LoadData(filename, &c)
 
 	if err != nil {
 		return nil, contextLoadingError(filename, err)
@@ -81,7 +81,17 @@ func LoadContextFromFile(filename string) (*Context, error) {
 func (ctx *Context) loadImportedVariables() error {
 	for _, file := range ctx.VariableImports {
 		var importedVars map[string]interface{}
-		err := util.LoadJsonOrYaml(path.Join(ctx.BaseDir, file), &importedVars)
+
+		// Ensure that the filename is not merged with the baseDir
+		// if it is set to the special value /dev/stdin
+		var filePath string
+		if file == "/dev/stdin" {
+			filePath = file
+		} else {
+			filePath = path.Join(ctx.BaseDir, file)
+		}
+
+		err := util.LoadData(filePath, &importedVars)
 
 		if err != nil {
 			return err
@@ -146,7 +156,7 @@ func loadDefaultValues(rs *ResourceSet, c *Context) *map[string]interface{} {
 	var defaultVars map[string]interface{}
 
 	for _, filename := range util.DefaultFilenames {
-		err := util.LoadJsonOrYaml(path.Join(c.BaseDir, rs.Path, filename), &defaultVars)
+		err := util.LoadData(path.Join(c.BaseDir, rs.Path, filename), &defaultVars)
 		if err == nil {
 			return util.Merge(&defaultVars, &rs.Values)
 		}
diff --git a/util/util.go b/util/util.go
index 947ab6e..3a1be52 100644
--- a/util/util.go
+++ b/util/util.go
@@ -10,11 +10,7 @@
 package util
 
 import (
-	"encoding/json"
-	"fmt"
 	"io/ioutil"
-	"strings"
-
 	"github.com/ghodss/yaml"
 )
 
@@ -45,19 +41,15 @@ func Merge(in1 *map[string]interface{}, in2 *map[string]interface{}) *map[string
 }
 
 // Loads either a YAML or JSON file from the specified path and deserialises it into the provided interface.
-func LoadJsonOrYaml(filename string, addr interface{}) error {
+func LoadData(filename string, addr interface{}) error {
 	file, err := ioutil.ReadFile(filename)
 	if err != nil {
 		return err
 	}
 
-	if strings.HasSuffix(filename, "json") {
-		err = json.Unmarshal(file, addr)
-	} else if strings.HasSuffix(filename, "yaml") || strings.HasSuffix(filename, "yml") {
-		err = yaml.Unmarshal(file, addr)
-	} else {
-		return fmt.Errorf("File format not supported. Must be JSON or YAML.")
+	err = yaml.Unmarshal(file, addr)
+	if err != nil {
+		return err
 	}
-
 	return nil
 }
```

Which simply takes your JSON/YAML change and (importantly) removes the filename restriction.

You can then write this `context.yaml`:

```yaml
import:
  - /dev/stdin
include:
  - name: foobar
    values:
      foo: bar
```

With this template:

```
Foo is {{ .foo }}.
Bar is {{ .bar }}.
```

And run:

```
$ echo "bar: '$(date)'" | kontemplate template context.yaml 
Loading resources for foobar
Rendered file foobar/template.yaml:
Foo is bar.
Bar is Wed May 16 09:48:15 CEST 2018.
```

**Comment by tazjin** [comment]
Hey! I'm opting for the slightly more flexible solution of supporting absolute paths to load variables from, which will let you load variables from standard input by specifying `/dev/stdin` as an import source.

Sorry for taking so long to get this dealt with, been busy with other stuff!

**Pull request closed without merging**
