### PR TITLE
Add template method to look up IP addresses from local DNS resolver

### PR DESCRIPTION
**Pull request by landro**
Using this for passing IP addresses to GKE Kubernetes Service (type LoadBalancer)

### CODE REVIEW

**Comment by tazjin** [comment]
Hey, thanks for the contribution!

I have a couple of comments on it:

1. You need to run `go fmt ./...` on the codebase to make it adhere to the Go code style.
2. This template function should probably have its own associated error type instead of the `PassError` which is used by the `passLookup` template function.
3. Go's template engine can handle list-like values, so it may not be necessary to just pick the first value but rather return the actual _list_ and use it like `{{ lookupIPAddr | first }}` in a template pipeline (where [first](http://masterminds.github.io/sprig/lists.html) is a different template function).

------

Apart from that it's an interesting PR, I just need to consider how I feel about having inputs that are not version-controllable themselves. That is sort of related to #62, but now that `passLookup` already exists I may be fine with adding another similar function. Need to meditate on this for the night :-)

**Comment by landro** [comment]
Sorry about the missing reformat (1) and stupid copy/paste error related to PassError (2). Those have been fixed.  Would it make sense to have a simple make file to build the project locally? I'm aware of go templates being able to handle lists, but I believe it makes sense to have a dedicated method since the use case for this is related to the following usage pattern, and using lists would make the template look ugly:

```
---
kind: Service
apiVersion: v1
spec:
  loadBalancerIP: {{ "kontemplate.works." | singleIPLookup }}
  type: LoadBalancer
 ```

**Comment by landro** [comment]
You know what, I agree with you about 3 too. Let me update the PR, @tazjin

**Comment by landro** [comment]
Please let me know if you have any further remarks, @tazjin

**Comment by tazjin** [comment]
Please excuse the slow response, lots of other stuff going on at the moment :-)

One more minor thing: Please amend the commit messages to fit the commit format of the rest of the project. I'm mostly sticking to the [Angular style guide](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) - you can see the existing history for an example.

I should probably have a `CONTRIBUTING.md` that makes this explicit, so thank you for implicitly pointing that out! ;-)

**Comment by landro** [comment]
Just squashed my commits into one and improved the commit message, @tazjin. Please let me know if you have further comments.

**Pull request merged**
