### PR TITLE
File include support for kontemplate

### PR DESCRIPTION
**Pull request by salkin**
- Include is relative to directory where kontemplate yaml is located.
- Example added to docs.

Implements #46

### CODE REVIEW

**Comment by tazjin** [comment]
Hey, thanks for the PR! I've been putting off work on this repo for a bit, but this is a good motivator ;-)

Gonna start by looking into the failed Travis build.

**Comment by tazjin** [comment]
@salkin In the unlikely case of a GPL-enforcement event it's much easier for me to have all copyright assigned to myself. If that is okay for you I will change the copyright header.

**Comment by salkin** [comment]
@tazjin sure that is ok.

**Comment by tazjin** [comment]
@salkin The feature is now on `master`, but the function is renamed to `insertFile` and the path is relative to the resource set (not the cluster config).

Sorry for the delay, I had some personal issues to deal with and didn't have much time for open-source maintenance during that!

**Pull request closed without merging**
