### PR TITLE
Add timestamp template function to return Unix time

### PR DESCRIPTION
**Pull request by noqcks**
Hey again! 

Just adding another template function so that we can tag resources with a timestamp. 

Im open to a different name if you don't like `timestamp` 

cc: @tazjin

### CODE REVIEW

**Comment by noqcks** [comment]
Not sure why the Nix build is failing 🤔

**Comment by tazjin** [comment]
> Not sure why the Nix build is failing

It seems like one of the dependencies is invoking GNU Parallel, which isn't installed in the build environment. I will take a look at that, it seems odd.

As for the pull request - I think this is already satisfied by sprig's [date functions](http://masterminds.github.io/sprig/date.html), which are available in kontemplate. As is par for the course for Go, using them in the way you intend is a bit confusing but basically boils down to the `now` template function returning a [`Time`](https://golang.org/pkg/time/#Time.Unix), which has an associated [`Unix`](https://golang.org/pkg/time/#Time.Unix) function that returns an epoch timestamp.

Put together, in a template:

```yaml
theTimestamp: {{ now.Unix }}
```

=>

```
theTimestamp: 1546933037
```

**Comment by noqcks** [comment]
Oh perfecto! I didn't know that was available in Sprig. I'll close this PR.

Thanks again for the project @tazjin, we've been using it on our team for the past year and it's been great!

**Comment by tazjin** [comment]
@noqcks Thanks for the feedback :slightly_smiling_face:

**Pull request closed without merging**
