### PR TITLE
fix(templater): add baseDir to gitHead cmd so that directory is overwritten

### PR DESCRIPTION
**Pull request by noqcks**
This makes it so that when gitHead is called in a template the git hash that is returned is the hash of the dir containing the template, not the hash of the dir where kontemplate is called.

resolves issue raised [here](https://github.com/tazjin/kontemplate/pull/123#issuecomment-377318961)

### CODE REVIEW

**Comment by tazjin** [comment]
Thanks for the PR!

**Comment by noqcks** [comment]
Np! When's the next release slated?

Sooner would be best for us. Thanks!

**Comment by tazjin** [comment]
@noqcks I see, I'll try to cut one tomorrow morning. There's another PR that I was hoping would get updated in time, but I assume the author is busy with other stuff for now.

**Comment by tazjin** [comment]
@noqcks Here you go: https://github.com/tazjin/kontemplate/releases/tag/v1.5.0

**Comment by noqcks** [comment]
thank you ! 🚢

**Pull request merged**
