### PR TITLE
Refactor, document and test value merging logic

### PR DESCRIPTION
**Pull request by tazjin**
Please see the individual commit messages in this pull request for additional information.

This relates to the discussion in issue #142. I've published a pre-release build of this version [here](https://storage.googleapis.com/files.tazj.in/kontemplate-1.7.0-rc1.tar.gz) (tarball includes builds for Linux, Darwin, FreeBSD and Windows).

cc: @merlineus @Arttii @tommyJimmy87

### CODE REVIEW

**Comment by Arttii** [comment]
I tested the branch. Its very understandable now from the comments, and the behavior is the one we were aiming for. Thanks for the  fix!!!

**Comment by tazjin** [comment]
@Arttii Thank you! I'm going to wait for feedback from @merlineus, too.

**Comment by merlineus** [comment]
Yeah!
Thanks for quick reaction. Overriding behaviour is now logical and clear for understanding :)

**Comment by merlineus** [comment]
@tazjin do you plan to release a minor version with this change? Maybe 1.6.1?

**Comment by tazjin** [comment]
@merlineus No, but I'm planning to release a major version with it (1.7.0) ;-)

Waiting to see if @tommyJimmy87 (who filed the original issue) has more input before moving forward.

**Pull request merged**
